import _get from 'lodash/get'

export default function handler(req, res) {
  if (req.method !== 'POST') {
    res.status(405).send({ message: 'Only POST requests allowed' })
    return
  }

  const json = req.body
  const inputText = _get(json, 'inputText')

  if (!inputText) {
    res.status(400).send({ message: 'must pass inputText' })
    return
  }

  res.status(200).json({
    received: inputText,
    status: 'ai',
    text: 'The text was generated by an ai',
  })
}
